qca-nss-crypto: Fix build issues with gcc5.2
Currently when we try to build this package with gcc5.2
then we get below error message:
error: macro "__TIME__" might prevent reproducible builds [-Werror=date-time]

Since __TIME__ and __DATE__ macros does not seem much helpfull,
so removing them and adding jiffies in ms to print.

Change-Id: I838c188cdfa59ff164e6408029532ae8c1835917
Signed-off-by: Ram Chandra Jangir <rjangi@codeaurora.org>